services:
  invoices-pg:
    image: bitnami/postgresql:latest
    ports:
      - '5483:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=invoices
    volumes: #roda os scripts sql da pasta docker asism que sobe o container
      - ./docker:/docker-entrypoint-initdb.d