_format_version: "3.0"
_transform: true

services:
  - name: orders
    url: ${ORDERS_SERVICE_URL}
    path: /
    routes:
      - name: api-orders
        protocols:
          - http
          - https
        paths:
          - /orders

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Content-Type
        - Authorization